server:
  port: 18888

spring:
  profiles:
    active: dev

logging:
  level:
    com:
      monkey:
        common:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.monkey.common.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

