spring:
  datasource:
    # 自动执行sql脚本
    initialization-mode: always
    schema: classpath:monkey-ddl.sql
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/monkey-admin?useSSL=true&characterEncoding=UTF-8
      username: root
      password: luffy1994
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      # Spring监控配置
      aop-patterns: com.monkey.framework.service.*
      # 配置监控统计拦截的filters
      filters: config,stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false
        allow: 127.0.0.1
      # 配置监控属性
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
        profile-enable: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
      # 慢SQL
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1