server:
  port: 18888

spring:
  profiles:
    active: dev

logging:
  level:
    com:
      monkey:
        business:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.monkey.business.entity

